export const data = [
  {
    categoryId: 1,
    categoryName: "EPR Authorization",
    categorySlug: "epr-authorization",
    description: "<p>EPR registration helps manage waste effectively and ensures environmental safety.</p>",
    id: 2,
    image: "src/assets/recycle.png",
    metaDescription: "Learn about EPR compliance and waste management.",
    metaKeyword: "epr compliance, waste management",
    metaTitle: "EPR Compliance Guide",
    postDate: "01-01-2026 10:00:00",
    postedByName: "Admin",
    relatedServiceTitles: ["EPR Registration"],
    slug: "epr-compliance-guide",
    subcategoryId: 1,
    subcategoryName: "EPR Plastic Waste Management",
    subcategorySlug: "epr-plastic-waste-management",
    summary: "Artificial Intelligence is transforming the way people live and work across the world. From healthcare to education, AI-powered systems help improve efficiency, accuracy, and decision-making. In healthcare, AI assists doctors in diagnosing diseases earlier, while in education it personalizes learning experiences for students. Businesses use AI to automate repetitive tasks, saving time and reducing costs. However, the rapid growth of AI also raises concerns about data privacy, job displacement, and ethical use. To ensure its benefits are maximized, it is important to develop responsible AI systems that are transparent, fair, and aligned with human values.",
    title: "EPR Compliance Guide",
    uuid: "uuid-2",
    visited: 10
  },
  {
    categoryId: 1,
    categoryName: "EPR Authorization",
    categorySlug: "epr-authorization",
    description: "<p>Plastic waste rules ensure proper recycling and disposal.</p>",
    id: 3,
    image: "src/assets/recycle-dark.png",
    metaDescription: "Plastic waste management rules explained.",
    metaKeyword: "plastic waste, recycling",
    metaTitle: "Plastic Waste Rules",
    postDate: "02-01-2026 11:00:00",
    postedByName: "Admin",
    relatedServiceTitles: ["Plastic EPR"],
    slug: "plastic-waste-rules",
    subcategoryId: 1,
    subcategoryName: "EPR Plastic Waste Management",
    subcategorySlug: "epr-plastic-waste-management",
    summary: "Overview of plastic waste rules.",
    title: "Plastic Waste Rules",
    uuid: "uuid-3",
    visited: 20
  },
  {
    categoryId: 1,
    categoryName: "EPR Authorization",
    categorySlug: "epr-authorization",
    description: "<p>E-waste recycling helps reduce environmental pollution.</p>",
    id: 4,
    image: "/images/blog/e-waste.jpg",
    metaDescription: "E-waste recycling process and benefits.",
    metaKeyword: "e-waste, recycling",
    metaTitle: "E-Waste Recycling",
    postDate: "03-01-2026 12:00:00",
    postedByName: "Admin",
    relatedServiceTitles: ["E-Waste Management"],
    slug: "e-waste-recycling",
    subcategoryId: 1,
    subcategoryName: "EPR Plastic Waste Management",
    subcategorySlug: "epr-plastic-waste-management",
    summary: "Steps in e-waste recycling.",
    title: "E-Waste Recycling",
    uuid: "uuid-4",
    visited: 15
  },
  {
    categoryId: 1,
    categoryName: "EPR Authorization",
    categorySlug: "epr-authorization",
    description: "<p>Sustainability helps businesses grow responsibly.</p>",
    id: 5,
    image: "/images/blog/sustainability.jpg",
    metaDescription: "Importance of sustainability.",
    metaKeyword: "sustainability, environment",
    metaTitle: "Sustainability in Business",
    postDate: "04-01-2026 13:00:00",
    postedByName: "Admin",
    relatedServiceTitles: ["Sustainability"],
    slug: "sustainability-business",
    subcategoryId: 1,
    subcategoryName: "EPR Plastic Waste Management",
    subcategorySlug: "epr-plastic-waste-management",
    summary: "Why sustainability matters.",
    title: "Sustainability in Business",
    uuid: "uuid-5",
    visited: 18
  },
  {
    categoryId: 1,
    categoryName: "EPR Authorization",
    categorySlug: "epr-authorization",
    description: "<p>Waste segregation reduces landfill pressure.</p>",
    id: 6,
    image: "/images/blog/waste-segregation.jpg",
    metaDescription: "Waste segregation tips.",
    metaKeyword: "waste segregation",
    metaTitle: "Waste Segregation",
    postDate: "05-01-2026 14:00:00",
    postedByName: "Admin",
    relatedServiceTitles: ["Waste Management"],
    slug: "waste-segregation",
    subcategoryId: 1,
    subcategoryName: "EPR Plastic Waste Management",
    subcategorySlug: "epr-plastic-waste-management",
    summary: "How to segregate waste.",
    title: "Waste Segregation",
    uuid: "uuid-6",
    visited: 25
  },
  {
    categoryId: 1,
    categoryName: "EPR Authorization",
    categorySlug: "epr-authorization",
    description: "<p>Circular economy promotes reuse and recycling.</p>",
    id: 7,
    image: "/images/blog/circular-economy.jpg",
    metaDescription: "Circular economy basics.",
    metaKeyword: "circular economy",
    metaTitle: "Circular Economy",
    postDate: "06-01-2026 15:00:00",
    postedByName: "Admin",
    relatedServiceTitles: ["Recycling"],
    slug: "circular-economy",
    subcategoryId: 1,
    subcategoryName: "EPR Plastic Waste Management",
    subcategorySlug: "epr-plastic-waste-management",
    summary: "Introduction to circular economy.",
    title: "Circular Economy",
    uuid: "uuid-7",
    visited: 30
  },
  {
    categoryId: 1,
    categoryName: "EPR Authorization",
    categorySlug: "epr-authorization",
    description: "<p>Battery waste requires safe disposal methods.</p>",
    id: 8,
    image: "/images/blog/battery-waste.jpg",
    metaDescription: "Battery waste handling.",
    metaKeyword: "battery waste",
    metaTitle: "Battery Waste Management",
    postDate: "07-01-2026 16:00:00",
    postedByName: "Admin",
    relatedServiceTitles: ["Battery EPR"],
    slug: "battery-waste-management",
    subcategoryId: 1,
    subcategoryName: "EPR Plastic Waste Management",
    subcategorySlug: "epr-plastic-waste-management",
    summary: "Handling battery waste.",
    title: "Battery Waste Management",
    uuid: "uuid-8",
    visited: 12
  },
  {
    categoryId: 1,
    categoryName: "EPR Authorization",
    categorySlug: "epr-authorization",
    description: "<p>CPCB regulates EPR compliance in India.</p>",
    id: 9,
    image: "/images/blog/cpcb.jpg",
    metaDescription: "Role of CPCB.",
    metaKeyword: "cpcb, epr",
    metaTitle: "Role of CPCB",
    postDate: "08-01-2026 17:00:00",
    postedByName: "Admin",
    relatedServiceTitles: ["Compliance"],
    slug: "role-of-cpcb",
    subcategoryId: 1,
    subcategoryName: "EPR Plastic Waste Management",
    subcategorySlug: "epr-plastic-waste-management",
    summary: "CPCB responsibilities.",
    title: "Role of CPCB",
    uuid: "uuid-9",
    visited: 40
  },
  {
    categoryId: 1,
    categoryName: "EPR Authorization",
    categorySlug: "epr-authorization",
    description: "<p>Recycling plastic reduces environmental damage.</p>",
    id: 10,
    image: "/images/blog/plastic-recycling.jpg",
    metaDescription: "Plastic recycling benefits.",
    metaKeyword: "plastic recycling",
    metaTitle: "Plastic Recycling",
    postDate: "09-01-2026 18:00:00",
    postedByName: "Admin",
    relatedServiceTitles: ["Recycling"],
    slug: "plastic-recycling",
    subcategoryId: 1,
    subcategoryName: "EPR Plastic Waste Management",
    subcategorySlug: "epr-plastic-waste-management",
    summary: "Benefits of recycling plastic.",
    title: "Plastic Recycling",
    uuid: "uuid-10",
    visited: 22
  },
  {
    categoryId: 1,
    categoryName: "EPR Authorization",
    categorySlug: "epr-authorization",
    description: "<p>Green practices help reduce carbon footprint.</p>",
    id: 11,
    image: "/images/blog/green-practices.jpg",
    metaDescription: "Green business practices.",
    metaKeyword: "green business",
    metaTitle: "Green Practices",
    postDate: "10-01-2026 19:00:00",
    postedByName: "Admin",
    relatedServiceTitles: ["Sustainability"],
    slug: "green-practices",
    subcategoryId: 1,
    subcategoryName: "EPR Plastic Waste Management",
    subcategorySlug: "epr-plastic-waste-management",
    summary: "Eco-friendly business tips.",
    title: "Green Practices",
    uuid: "uuid-11",
    visited: 35
  }
];